apiVersion: v1
kind: Secret
metadata:
  name: erp-secrets
type: Opaque
stringData:
  database-url: "mysql://user:password@mysql-service:3306/collegeerp?connection_limit=5"

  gemini-api-key: "your_gemini_api_key"
  jwt-access-secret: "Vd0P3glxth3WvEAvaU9WrKm2scIx9TUM7o7dBtKGRhw="
  jwt-refresh-secret: "hhcKlNChIWwFRi/yvFLUSS6w32+SRe1kfAwXwc/rE94="
